using Keryx.Core;

namespace Keryx.Sctp;

/// <summary>Type codes for the parameters carried by a RE-CONFIG chunk (RFC 6525 §4).</summary>
public enum SctpReconfigParameterType : ushort
{
    /// <summary>Outgoing SSN Reset Request (RFC 6525 §4.1).</summary>
    OutgoingSsnResetRequest = 13,

    /// <summary>Incoming SSN Reset Request (RFC 6525 §4.2).</summary>
    IncomingSsnResetRequest = 14,

    /// <summary>SSN/TSN Reset Request (RFC 6525 §4.3). Not generated by Keryx.</summary>
    SsnTsnResetRequest = 15,

    /// <summary>Re-configuration Response (RFC 6525 §4.4).</summary>
    ReconfigResponse = 16,

    /// <summary>Add Outgoing Streams Request (RFC 6525 §4.5). Not generated by Keryx.</summary>
    AddOutgoingStreamsRequest = 17,

    /// <summary>Add Incoming Streams Request (RFC 6525 §4.6). Not generated by Keryx.</summary>
    AddIncomingStreamsRequest = 18,
}

/// <summary>Result codes carried by a Re-configuration Response Parameter (RFC 6525 §4.4).</summary>
public enum SctpReconfigResult : uint
{
    /// <summary>The request was valid but there was nothing to reset.</summary>
    SuccessNothingToDo = 0,

    /// <summary>The requested reset was performed.</summary>
    SuccessPerformed = 1,

    /// <summary>The request was denied.</summary>
    Denied = 2,

    /// <summary>The request referenced a stream sequence number that was wrong.</summary>
    ErrorWrongSsn = 3,

    /// <summary>An identical request is already being processed.</summary>
    ErrorRequestAlreadyInProgress = 4,

    /// <summary>The request sequence number was out of range.</summary>
    ErrorBadSequenceNumber = 5,

    /// <summary>The reset could not be performed yet and is in progress.</summary>
    InProgress = 6,
}

/// <summary>
/// Base class for the type-length-value parameters carried by a RE-CONFIG chunk (RFC 6525 §4).
/// The length field covers the four header bytes and the value but not the alignment padding.
/// </summary>
public abstract class SctpReconfigParameter
{
    /// <summary>The parameter type code.</summary>
    public abstract SctpReconfigParameterType Type { get; }

    /// <summary>Length of the parameter value, excluding the four-byte TLV header and padding.</summary>
    public abstract int ValueLength { get; }

    /// <summary>Encoded length in bytes excluding trailing padding — the value of the length field.</summary>
    public int Length => 4 + ValueLength;

    /// <summary>Encoded length rounded up to the next four-byte boundary.</summary>
    public int PaddedLength => (Length + 3) & ~3;

    /// <summary>Writes the parameter value (everything after the four-byte TLV header).</summary>
    /// <param name="writer">Destination writer.</param>
    public abstract void WriteValue(ref ByteWriter writer);

    /// <summary>Writes the parameter, including alignment padding, to <paramref name="writer"/>.</summary>
    /// <param name="writer">Destination writer.</param>
    public void WriteTo(ref ByteWriter writer)
    {
        writer.WriteU16((ushort)Type);
        writer.WriteU16((ushort)Length);
        WriteValue(ref writer);
        writer.WriteZero(PaddedLength - Length);
    }

    /// <summary>Parses a single RE-CONFIG parameter from its type code and value bytes.</summary>
    /// <param name="type">Parameter type code.</param>
    /// <param name="value">Parameter value, excluding the header and padding.</param>
    /// <returns>The parsed parameter, or an <see cref="SctpUnknownReconfigParameter"/> for unknown types.</returns>
    /// <exception cref="ByteBufferException">The value is truncated for the declared type.</exception>
    public static SctpReconfigParameter Parse(ushort type, ReadOnlySpan<byte> value) =>
        (SctpReconfigParameterType)type switch
        {
            SctpReconfigParameterType.OutgoingSsnResetRequest => SctpOutgoingSsnResetRequest.ParseValue(value),
            SctpReconfigParameterType.IncomingSsnResetRequest => SctpIncomingSsnResetRequest.ParseValue(value),
            SctpReconfigParameterType.ReconfigResponse => SctpReconfigResponse.ParseValue(value),
            _ => new SctpUnknownReconfigParameter(type, value.ToArray()),
        };

    /// <summary>Parses a sequence of RE-CONFIG parameters that fills <paramref name="body"/>.</summary>
    /// <param name="body">Buffer holding one or more consecutive parameters.</param>
    /// <returns>The parsed parameters in wire order.</returns>
    /// <exception cref="ByteBufferException">The buffer is truncated or a length field is invalid.</exception>
    public static List<SctpReconfigParameter> ParseAll(ReadOnlySpan<byte> body)
    {
        var result = new List<SctpReconfigParameter>();
        var offset = 0;
        while (body.Length - offset >= 4)
        {
            var type = (ushort)((body[offset] << 8) | body[offset + 1]);
            var length = (ushort)((body[offset + 2] << 8) | body[offset + 3]);
            if (length < 4 || offset + length > body.Length)
            {
                throw new ByteBufferException(
                    $"RE-CONFIG parameter 0x{type:X4} declares length {length} at offset {offset} but only {body.Length - offset} byte(s) remain.");
            }

            result.Add(Parse(type, body.Slice(offset + 4, length - 4)));
            var padded = (length + 3) & ~3;
            offset += Math.Min(padded, body.Length - offset);
        }

        return result;
    }
}

/// <summary>An Outgoing SSN Reset Request Parameter (RFC 6525 §4.1).</summary>
public sealed class SctpOutgoingSsnResetRequest : SctpReconfigParameter
{
    /// <summary>Creates an Outgoing SSN Reset Request.</summary>
    /// <param name="requestSequence">The sender's request sequence number for this request.</param>
    /// <param name="responseSequence">The last received request sequence number this responds to, or the sender's expected response sequence minus one.</param>
    /// <param name="sendersLastAssignedTsn">The last TSN the sender assigned before requesting the reset.</param>
    /// <param name="streams">The outgoing stream identifiers to reset; an empty list resets every stream.</param>
    public SctpOutgoingSsnResetRequest(uint requestSequence, uint responseSequence, uint sendersLastAssignedTsn, IReadOnlyList<ushort> streams)
    {
        ArgumentNullException.ThrowIfNull(streams);
        RequestSequence = requestSequence;
        ResponseSequence = responseSequence;
        SendersLastAssignedTsn = sendersLastAssignedTsn;
        Streams = streams;
    }

    /// <inheritdoc />
    public override SctpReconfigParameterType Type => SctpReconfigParameterType.OutgoingSsnResetRequest;

    /// <summary>The sender's request sequence number.</summary>
    public uint RequestSequence { get; }

    /// <summary>The response sequence number acknowledging the peer's last request.</summary>
    public uint ResponseSequence { get; }

    /// <summary>The last TSN the sender assigned; the receiver defers the reset until it has received up to this TSN.</summary>
    public uint SendersLastAssignedTsn { get; }

    /// <summary>The outgoing stream identifiers to reset; empty means all streams.</summary>
    public IReadOnlyList<ushort> Streams { get; }

    /// <inheritdoc />
    public override int ValueLength => 12 + (Streams.Count * 2);

    /// <inheritdoc />
    public override void WriteValue(ref ByteWriter writer)
    {
        writer.WriteU32(RequestSequence);
        writer.WriteU32(ResponseSequence);
        writer.WriteU32(SendersLastAssignedTsn);
        foreach (var stream in Streams)
        {
            writer.WriteU16(stream);
        }
    }

    internal static SctpOutgoingSsnResetRequest ParseValue(ReadOnlySpan<byte> value)
    {
        var reader = new ByteReader(value);
        var requestSequence = reader.ReadU32();
        var responseSequence = reader.ReadU32();
        var lastAssignedTsn = reader.ReadU32();
        var streams = new List<ushort>();
        while (reader.Remaining >= 2)
        {
            streams.Add(reader.ReadU16());
        }

        return new SctpOutgoingSsnResetRequest(requestSequence, responseSequence, lastAssignedTsn, streams);
    }
}

/// <summary>An Incoming SSN Reset Request Parameter (RFC 6525 §4.2).</summary>
public sealed class SctpIncomingSsnResetRequest : SctpReconfigParameter
{
    /// <summary>Creates an Incoming SSN Reset Request.</summary>
    /// <param name="requestSequence">The sender's request sequence number for this request.</param>
    /// <param name="streams">The incoming stream identifiers (from the sender's view) to reset; empty means all.</param>
    public SctpIncomingSsnResetRequest(uint requestSequence, IReadOnlyList<ushort> streams)
    {
        ArgumentNullException.ThrowIfNull(streams);
        RequestSequence = requestSequence;
        Streams = streams;
    }

    /// <inheritdoc />
    public override SctpReconfigParameterType Type => SctpReconfigParameterType.IncomingSsnResetRequest;

    /// <summary>The sender's request sequence number.</summary>
    public uint RequestSequence { get; }

    /// <summary>The stream identifiers the sender asks this endpoint to reset on its outgoing side; empty means all.</summary>
    public IReadOnlyList<ushort> Streams { get; }

    /// <inheritdoc />
    public override int ValueLength => 4 + (Streams.Count * 2);

    /// <inheritdoc />
    public override void WriteValue(ref ByteWriter writer)
    {
        writer.WriteU32(RequestSequence);
        foreach (var stream in Streams)
        {
            writer.WriteU16(stream);
        }
    }

    internal static SctpIncomingSsnResetRequest ParseValue(ReadOnlySpan<byte> value)
    {
        var reader = new ByteReader(value);
        var requestSequence = reader.ReadU32();
        var streams = new List<ushort>();
        while (reader.Remaining >= 2)
        {
            streams.Add(reader.ReadU16());
        }

        return new SctpIncomingSsnResetRequest(requestSequence, streams);
    }
}

/// <summary>A Re-configuration Response Parameter (RFC 6525 §4.4).</summary>
public sealed class SctpReconfigResponse : SctpReconfigParameter
{
    /// <summary>Creates a Re-configuration Response with no optional TSN fields.</summary>
    /// <param name="responseSequence">The request sequence number this response acknowledges.</param>
    /// <param name="result">The result of the requested reconfiguration.</param>
    public SctpReconfigResponse(uint responseSequence, SctpReconfigResult result)
    {
        ResponseSequence = responseSequence;
        Result = result;
    }

    /// <summary>Creates a Re-configuration Response carrying the optional Sender's/Receiver's Next TSN fields.</summary>
    /// <param name="responseSequence">The request sequence number this response acknowledges.</param>
    /// <param name="result">The result of the requested reconfiguration.</param>
    /// <param name="sendersNextTsn">The sender's next TSN.</param>
    /// <param name="receiversNextTsn">The receiver's next TSN.</param>
    public SctpReconfigResponse(uint responseSequence, SctpReconfigResult result, uint sendersNextTsn, uint receiversNextTsn)
    {
        ResponseSequence = responseSequence;
        Result = result;
        SendersNextTsn = sendersNextTsn;
        ReceiversNextTsn = receiversNextTsn;
        HasTsnFields = true;
    }

    /// <inheritdoc />
    public override SctpReconfigParameterType Type => SctpReconfigParameterType.ReconfigResponse;

    /// <summary>The request sequence number this response acknowledges.</summary>
    public uint ResponseSequence { get; }

    /// <summary>The result of the requested reconfiguration.</summary>
    public SctpReconfigResult Result { get; }

    /// <summary>True when the optional Sender's/Receiver's Next TSN fields are present.</summary>
    public bool HasTsnFields { get; }

    /// <summary>The sender's next TSN, valid only when <see cref="HasTsnFields"/> is true.</summary>
    public uint SendersNextTsn { get; }

    /// <summary>The receiver's next TSN, valid only when <see cref="HasTsnFields"/> is true.</summary>
    public uint ReceiversNextTsn { get; }

    /// <inheritdoc />
    public override int ValueLength => HasTsnFields ? 16 : 8;

    /// <inheritdoc />
    public override void WriteValue(ref ByteWriter writer)
    {
        writer.WriteU32(ResponseSequence);
        writer.WriteU32((uint)Result);
        if (HasTsnFields)
        {
            writer.WriteU32(SendersNextTsn);
            writer.WriteU32(ReceiversNextTsn);
        }
    }

    internal static SctpReconfigResponse ParseValue(ReadOnlySpan<byte> value)
    {
        var reader = new ByteReader(value);
        var responseSequence = reader.ReadU32();
        var result = (SctpReconfigResult)reader.ReadU32();
        if (reader.Remaining >= 8)
        {
            return new SctpReconfigResponse(responseSequence, result, reader.ReadU32(), reader.ReadU32());
        }

        return new SctpReconfigResponse(responseSequence, result);
    }
}

/// <summary>A RE-CONFIG parameter whose type Keryx does not decode, retained so the chunk round-trips.</summary>
public sealed class SctpUnknownReconfigParameter : SctpReconfigParameter
{
    private readonly ushort _type;

    /// <summary>Creates an unknown RE-CONFIG parameter.</summary>
    /// <param name="type">The raw parameter type code.</param>
    /// <param name="value">The undecoded parameter value; stored by reference, not copied.</param>
    public SctpUnknownReconfigParameter(ushort type, byte[] value)
    {
        ArgumentNullException.ThrowIfNull(value);
        _type = type;
        Value = value;
    }

    /// <inheritdoc />
    public override SctpReconfigParameterType Type => (SctpReconfigParameterType)_type;

    /// <summary>The raw type code, which may not correspond to any known parameter.</summary>
    public ushort RawType => _type;

    /// <summary>The undecoded parameter value.</summary>
    public byte[] Value { get; }

    /// <inheritdoc />
    public override int ValueLength => Value.Length;

    /// <inheritdoc />
    public override void WriteValue(ref ByteWriter writer) => writer.WriteBytes(Value);
}

/// <summary>
/// A RE-CONFIG chunk (RFC 6525 §3.1), chunk type 130. Carries one or two Re-configuration
/// Parameters used to reset stream sequence numbers so a data channel's stream identifier can be
/// freed and reused.
/// </summary>
public sealed class SctpReConfigChunk : SctpChunk
{
    /// <summary>Creates an empty RE-CONFIG chunk.</summary>
    public SctpReConfigChunk()
    {
    }

    /// <summary>Creates a RE-CONFIG chunk carrying the given parameters.</summary>
    /// <param name="parameters">The parameters to carry, in wire order.</param>
    public SctpReConfigChunk(params SctpReconfigParameter[] parameters)
    {
        ArgumentNullException.ThrowIfNull(parameters);
        Parameters.AddRange(parameters);
    }

    /// <inheritdoc />
    public override SctpChunkType Type => SctpChunkType.ReConfig;

    /// <summary>The Re-configuration Parameters carried by this chunk, in wire order.</summary>
    public List<SctpReconfigParameter> Parameters { get; } = new();

    /// <inheritdoc />
    public override int BodyLength
    {
        get
        {
            var length = 0;
            foreach (var parameter in Parameters)
            {
                length += parameter.PaddedLength;
            }

            return length;
        }
    }

    /// <inheritdoc />
    public override void WriteBody(ref ByteWriter writer)
    {
        foreach (var parameter in Parameters)
        {
            parameter.WriteTo(ref writer);
        }
    }

    internal static SctpReConfigChunk ParseBody(ReadOnlySpan<byte> body)
    {
        var chunk = new SctpReConfigChunk();
        chunk.Parameters.AddRange(SctpReconfigParameter.ParseAll(body));
        return chunk;
    }
}
