<Project>
  <Import Project="$(MSBuildThisFileDirectory)../Directory.Build.props" />
  <PropertyGroup>
    <IsPackable>true</IsPackable>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <Authors>Keryx contributors</Authors>
    <Copyright>Copyright (c) Keryx contributors</Copyright>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
    <RepositoryUrl>https://github.com/Proxeno/keryx</RepositoryUrl>
    <PackageProjectUrl>https://github.com/Proxeno/keryx</PackageProjectUrl>
    <RepositoryType>git</RepositoryType>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <VersionPrefix>0.1.0</VersionPrefix>
    <VersionSuffix Condition="'$(VersionSuffix)' == '' and '$(CI)' != 'true'">dev</VersionSuffix>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageTags>webrtc;rtp;rtcp;srtp;stun;ice;sdp;dtls;sctp;dotnet</PackageTags>
  </PropertyGroup>
  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="/" />
  </ItemGroup>
</Project>
